## **Loading the Data**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv ('C:\\Users\\LENOVO\\Videos\\customer_shopping_behavior.csv')

df.head ()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [3]:
df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [4]:
df.isnull (). sum ()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

## **Need to deal with the nulls**

In [5]:
df['Gender'].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [6]:
df['Category'].unique()

array(['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear'],
      dtype=object)

In [7]:
df['Item Purchased'].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [8]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [9]:
df.groupby ('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

## **Category Mapping is needed as its mapped wrong**

In [10]:
correct_mapping = {
    'Accessories' : ['Sunglasses' , 'Gloves' , 'Jewelry' , 'Hat' , 'Backpack' , 'Belt' , 'Bag' , 'Scarf' , 'Watch' , 'Socks' , 'Handbag'],
    'Footwear' : ['Boots' , 'Shoes' , 'Sandals' , 'Slippers' , 'Sneakers'],
    'Electronics' : ['Laptop' , 'Phone' , 'Headphones'],
    'Clothing' : ['T-shirt' , 'Shirt' , 'Shorts' , 'Hoodie' , 'Pants' , 'Jeans' , 'Skirt' , 'Sweater' , 'Dress' , 'Blouse'],
    'Outerwear' : ['Coat' , 'Jacket']
}

In [11]:
# Create a flat mapping from item to category
item_to_category_map = {}
for category, items in correct_mapping.items():
    for item in items:
      item_to_category_map[item] = category

# Apply the mapping to the 'Category' column
df['Category'] = df['Item Purchased'].map(item_to_category_map)

In [12]:
df.groupby ('Category')['Item Purchased'].unique()

Category
Accessories    [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Socks, Bag, Belt, Watch, Scarf]
Clothing               [T-shirt, Shirt, Shorts, Hoodie, Pants, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                              [Laptop, Phone, Headphones]
Footwear                                                           [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                             [Coat, Jacket]
Name: Item Purchased, dtype: object

In [13]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [14]:
df['Size'].unique ()

array(['XL', 'M', 'L', 'S', nan], dtype=object)

In [15]:
df.groupby ('Category')['Size'].unique ()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

## **Assessories, Electronics and Footwear doesnt hvae sizes as M, L, XL etc**

In [16]:
df.loc [df['Category'] == 'Electronics' , 'Size'] = 'Not Applicable'

In [17]:
df.loc [df['Category'] == 'Accessories' , 'Size'] = 'Free Size'

In [18]:
df.loc [df['Category'] == 'Footwear' , 'Size'] = 'Not Available'

In [19]:
df.groupby ('Category')['Size'].unique ()

Category
Accessories           [Free Size]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear          [Not Available]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

## **Now Treating Null in Clothing**

In [20]:
df.loc [ (df['Category'] == 'Clothing') & (df['Size'].isnull()) , 'Size'] = df.loc [df['Category'] == 'Clothing' , 'Size'].mode()[0]

In [21]:
df.groupby ('Category')['Size'].unique ()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [Not Available]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

In [22]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [23]:
df.describe ()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [24]:
df['Purchase Amount (USD)'] = df['Purchase Amount (USD)'].fillna (df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

In [25]:
df.isnull (). sum ()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [26]:
df['Review Rating'].mean ()

np.float64(3.668195100022477)

In [27]:
df['Review Rating'].mode ()

0    4.0
Name: Review Rating, dtype: float64

In [28]:
df['Review Rating'] = df['Review Rating'].fillna (df.groupby('Item Purchased')['Review Rating'].transform('mean'))

df['Review Rating'] = df['Review Rating'].round ()

In [29]:
df.head ()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.0,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,4.0,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.0,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.0,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,4.0,No,Store Pickup,No,17.0,Credit Card,Weekly

In [30]:
df.isnull (). sum ()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [31]:
# Add a temporary column for the original index to preserve order within Customer ID groups
df_sorted = df.copy()
df_sorted['_original_index'] = df_sorted.index
df_sorted = df_sorted.sort_values(by=['Customer ID', '_original_index']).drop(columns=['_original_index'])

# Calculate the 'Purchase Amount (USD)' from the previous transaction for each customer.
# This will result in NaN for the first purchase of each customer within their group.
previous_purchase_amounts_shifted = df_sorted.groupby('Customer ID')['Purchase Amount (USD)'].shift(1)

# Align the shifted values back to the original DataFrame's index
previous_purchase_amounts_aligned = previous_purchase_amounts_shifted.reindex(df.index)

# Fill the NaN values in 'Previous Purchases' with these calculated amounts.
# Only fill where 'Previous Purchases' was originally NaN.
df['Previous Purchases'] = df['Previous Purchases'].fillna(previous_purchase_amounts_aligned)

# Fill any remaining NaN values (which are for the very first purchase of each customer)
# with 0, as per the requirement.
df['Previous Purchases'] = df['Previous Purchases'].fillna(0)

In [32]:
df.isnull ().sum ()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [33]:
df.head (20)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.00000,California,XL,Olive,Winter,3.0,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.00000,South Carolina,Free Size,White,Spring,4.0,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.00000,Montana,M,Black,Winter,3.0,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.00000,Illinois,Free Size,Red,Fall,4.0,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.00000,Alabama,Free Size,Yellow,Spring,4.0,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.00000,California,S,Beige,Summer,3.0,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.00000,Wisconsin,M,Brown,Summer,4.0,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.00000,Tennessee,Free Size,Purple,Summer,4.0,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.00000,Florida,Free Size,Red,Spring,4.0,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.00000,Kentucky,Free Size,Yellow,Winter,3.0,Yes,Store Pickup,Yes,7.0,Cash,Monthly
10,4568,35,Other,Shoes,Footwear,276.34379,Phoenix,Not Available,Blue,Autumn,4.0,No,Express,Yes,41.0,Credit Card,Monthly
11,947,46,Male,Coat,Outerwear,24.00000,Pennsylvania,XL,Blue,Spring,3.0,Yes,Next Day Air,Yes,4.0,PayPal,Quarterly
12,4776,64,Other,Laptop,Electronics,884.04000,Los Angeles,Not Applicable,Black,Spring,3.0,No,Express,No,0.0,Credit Card,Quarterly
13,3855,57,Female,T-shirt,Clothing,20.00000,Florida,M,Black,Spring,4.0,No,Free Shipping,No,4.0,Venmo,Annually
14,481,68,Male,Hoodie,Clothing,88.00000,Vermont,M,Gray,Summer,5.0,Yes,Standard,Yes,30.0,Debit Card,Bi-Weekly
15,3790,56,Female,Shirt,Clothing,75.00000,North Dakota,M,Magenta,Summer,4.0,No,Express,No,18.0,Bank Transfer,Every 3 Months
16,3617,42,Female,Hoodie,Clothing,23.00000,Wisconsin,L,Purple,Winter,3.0,No,Store Pickup,No,33.0,Debit Card,Fortnightly
17,2659,52,Female,Handbag,Accessories,47.00000,Ohio,Free Size,Indigo,Summer,3.0,No,Next Day Air,No,39.0,PayPal,Monthly
18,3725,30,Female,Gloves,Accessories,71.00000,Colorado,Free Size,Green,Winter,3.0,No,Express,No,18.0,Bank Transfer,Annually
19,2134,21,Male,Hat,Accessories,34.00000,Maine,Free Size,Olive,Summer,4.0,No,Standard,No,13.0,Bank Transfer,Annually

In [34]:
df.duplicated ().sum ()

np.int64(50)

## **Drop Duplicates**

In [35]:
df.drop_duplicates (inplace = True)

## **Renaming Headers**

In [36]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [37]:
df.columns = df.columns.str.replace (" " , "_")
df.columns = df.columns.str.lower ()

In [38]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [39]:
df = df.rename (columns = {'purchase_amount_(usd)' : 'purchase_amount'})

In [40]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [41]:
df.head ()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.0,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,4.0,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.0,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.0,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,4.0,No,Store Pickup,No,17.0,Credit Card,Weekly

In [48]:
df['subscription_status'].unique()

array(['No', 'Yes'], dtype=object)

In [49]:
df['shipping_type'].unique()

array(['Standard', 'Free Shipping', '2-Day Shipping', 'Store Pickup',
       'Express', 'Next Day Air'], dtype=object)

In [50]:
df['discount_applied'].unique()

array(['No', 'Yes'], dtype=object)

In [53]:
df['payment_method'].unique()

array(['Cash', 'Debit Card', 'Credit Card', 'PayPal', 'Venmo',
       'Bank Transfer'], dtype=object)

In [51]:
df['frequency_of_purchases'].unique()

array(['Weekly', 'Quarterly', 'Monthly', 'Annually', 'Every 3 Months',
       'Bi-Weekly', 'Fortnightly'], dtype=object)

## **Cleaning Done**

## **Connecting to MySQL**

In [42]:
!pip install --upgrade pymysql sqlalchemy pyngrok

Requirement already satisfied: pymysql in c:\users\lenovo\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\lenovo\anaconda3\lib\site-packages (2.0.49)
Requirement already satisfied: pyngrok in c:\users\lenovo\anaconda3\lib\site-packages (8.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: PyYAML>=5.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pyngrok) (6.0.3)

In [43]:
from pyngrok import ngrok

ngrok.set_auth_token ('3AWzfonaTJBUon68uNXsnmKj0Se_3kccRoygHWBiFu7QU4sB8')

In [46]:
from sqlalchemy import create_engine

username = "root"
password = "root123"
host = "localhost"
port = 3306
database = "customer_behaviour"

engine = create_engine (
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

try:
    conn = engine.connect()
    print ("Connected to MySQL")
    conn.close()

except Exception as e:
    print ("Connection Failed: " , e)

Connected to MySQL

In [47]:
from sqlalchemy import text

with engine.connect() as conn:

    conn.execute(text("""
        DROP TABLE IF EXISTS customer_data;
    """))

    conn.execute(text("""
        CREATE TABLE customer_data (
            customer_id INT,
            age INT,
            gender VARCHAR(10),
            item_purchased VARCHAR(255),
            category VARCHAR(100),
            purchase_amount FLOAT,
            location VARCHAR(100),
            size VARCHAR(50),
            color VARCHAR(50),
            season VARCHAR(50),
            review_rating FLOAT,
            subscription_status VARCHAR(20),
            shipping_type VARCHAR(50),
            discount_applied VARCHAR(10),
            previous_purchases FLOAT,
            payment_method VARCHAR(50),
            frequency_of_purchases VARCHAR(50)
        );
    """))

    conn.commit()
    print("✅ Table created manually")

✅ Table created manually

In [54]:
df.to_sql(
    "customer_data",
    con=engine,
    if_exists="append",
    index=False
)

print("✅ Data inserted successfully")

✅ Data inserted successfully

In [55]:
import pandas as pd

df_check = pd.read_sql("SELECT * FROM customer_data LIMIT 5;", engine)
print(df_check)

   customer_id  age  gender item_purchased     category  purchase_amount  \
0         2701   22  Female        T-shirt     Clothing             68.0
1          521   51    Male     Sunglasses  Accessories             84.0
2         3157   18  Female          Shirt     Clothing             50.0
3         1687   22    Male         Gloves  Accessories             75.0
4         2929   40  Female        Jewelry  Accessories             80.0

         location       size   color  season  review_rating  \
0      California         XL   Olive  Winter            3.0
1  South Carolina  Free Size   White  Spring            4.0
2         Montana          M   Black  Winter            3.0
3        Illinois  Free Size     Red    Fall            4.0
4         Alabama  Free Size  Yellow  Spring            4.0

  subscription_status   shipping_type discount_applied  previous_purchases  \
0                  No        Standard               No                36.0
1                 Yes   Free Shipping              Yes                20.0
2                  No  2-Day Shipping               No                18.0
3                  No    Store Pickup               No                25.0
4                  No    Store Pickup               No                17.0

  payment_method frequency_of_purchases
0           Cash                 Weekly
1     Debit Card              Quarterly
2           Cash                Monthly
3           Cash               Annually
4    Credit Card                 Weekly

## **Successfully Uploaded Data to MYSQL**